Account/Profile backend APIs
atunney/pwa-capstone pull request #20
Opened 2022-11-15 04:24 UTC by Zhu-K

Implemented API calls for methods relating to profile / account:

- [x] update profile (PUT /account/{id})
- [x] view profile (GET /account/{id})
- [x] create account/profile (POST /auth/register)

Currently works with the WIP frontend for account registration and authentication (https://github.com/atunney/pwa-capstone/tree/feature-frontend-auth)

2022-11-15 20:58 UTC, harsh2204 requested changes
The serializers for Profile looks good. Please see my comments and let me know if the suggested changes make sense.

2022-11-15 20:58 UTC, harsh2204 commented on src/backend/backend/urls.py
>      re_path(r'^auth/', include('djoser.urls.jwt')),
We should probably comment out these endpoints since we implemented custom views for account management now. FYI these are all the endpoints we would be removing, we probably need some of these endpoints down the line, and they can be added back in when needed.
<img width="961" alt="image" src="https://user-images.githubusercontent.com/21202898/202021684-c5151c73-911a-4bb2-baaf-e6e28cb8f5fa.png">

Moreover, let's switch jwt auth to simple token based auth in line 67 so it's easier to implement in the frontend for the POC atleast.

2022-11-15 20:58 UTC, harsh2204 commented on src/backend/accounts/views.py
>  class ListProfile(APIView):
We probably need some filtering on this view, I'm not sure if this view is useful at all returning **all** the user profiles. We could potentially leave this as is, and do the filtering on the front-end but that would create more unnecessary changes.

2022-11-15 20:58 UTC, harsh2204 commented on src/backend/accounts/views.py
> +    authentication_classes = [authentication.JWTAuthentication]
If we're gonna use token auth, then this should be `TokenAuthentication`

2022-11-15 21:41 UTC, Zhu-K commented on src/backend/backend/urls.py
>      re_path(r'^auth/', include('djoser.urls.jwt')),
Any reason to switch from jwt? The frontend authentication is already implemented.

2022-11-15 21:42 UTC, Zhu-K commented on src/backend/accounts/views.py
>  class ListProfile(APIView):
It's a placeholder for now, for later when we want to get a list of users by shop and etc. Can clean things up later, would rather keep for now to use as reference.

2022-11-15 21:43 UTC, Zhu-K commented on src/backend/accounts/views.py
> +    authentication_classes = [authentication.JWTAuthentication]
Using JWT authentication for now in the front end so the current implementation works. TokenAuthentication would fail.

2022-11-16 21:59 UTC, harsh2204 approved these changes

2022-11-16 22:00 UTC, merged